name: Track GitHub Followers

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/track-followers.yml'
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  track-followers:
    runs-on: ubuntu-latest
    # Add permissions to the GITHUB_TOKEN
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # This is important for being able to push changes
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          # Fetch all history so git push works
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run follower tracking script
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GITHUB_USERNAME: lucifron28
          LOG_FILE_PATH: logs/followers_log.md
          FOLLOWERS_DATA_PATH: data/followers.json
        run: |
          python src/main.py

      - name: Commit and push changes
        run: |
          # Ensure directories exist
          mkdir -p logs data
          
          # Configure git identity
          git config --global user.email "lucifron28@gmail.com"
          git config --global user.name "Ron"

          mkdir -p logs data
          git clean -fd src/__pycache__

          git add logs/followers_log.md data/followers.json
          git diff --staged --quiet || git commit -m "Update followers log"

          # Use the token to set a new authenticated remote
          git remote set-url origin https://x-access-token:${PERSONAL_ACCESS_TOKEN}@github.com/lucifron28/github-followers-tracker.git

          git push origin main