name: Track GitHub Followers

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/track-followers.yml'

jobs:
  track-followers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run follower tracking script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python src/main.py

      - name: Commit and push changes
        run: |
          git config --local user.email "lucifron28@gmail.com"
          git config --local user.name "Ron"
          git add logs/followers_log.md data/followers.json
          git commit -m "Update followers log"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}